name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run dotnet application
      run: dotnet  /home/runner/work/MainMasterGenerator/MainMasterGenerator/MainMasterGenerator/bin/Release/netcoreapp3.1/MainMasterGenerator.dll
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: MainMasterGeneratorForSpiewnik2.0
      # Directory containing files to upload
        path: /home/runner/work/MainMasterGenerator/MainMasterGenerator/MainMasterGenerator/bin/Release/netcoreapp3.1/MainMasterGenerator.dll
      
