name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Chechout repository
      uses: actions/checkout@v2.3.1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Install dependencies
      run: dotnet restore $GITHUB_WORKSPACE/SonglistGenerator/SonglistGenerator.csproj
    
    - name: Build
      run: dotnet build $GITHUB_WORKSPACE/SonglistGenerator.sln --configuration Release --no-restore
      
    - name: Run SonglistGenerator
      run: dotnet  $GITHUB_WORKSPACE/SonglistGenerator/bin/Release/netcoreapp3.1/SonglistGenerator.dll $GITHUB_WORKSPACE/main $GITHUB_WORKSPACE/Songbook.zip
    
    - name: Upload SonglistGenerator.dll
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: SonglistGenerator DLL r${{github.run_number}}
      # Directory containing files to upload
        path: SonglistGenerator/bin/Release/netcoreapp3.1/SonglistGenerator.dll
        
    - name: Upload zip file with new main and master files
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: Songbook v2.0 r${{github.run_number}}
      # Directory containing files to upload
        path: Songbook.zip
      
